export enum FlatType {
  PISO = 'PISO',
  CASA = 'CASA',
  CASA_RURAL = 'CASA_RURAL',
  'BOX/PLAZA_DE_GARAJE' = 'BOX/PLAZA_DE_GARAJE',
  TERRENOS = 'TERRENOS',
  COMERCIAL = 'COMERCIAL',
  ÁTICO = 'ÁTICO',
  EDIFICIO = 'EDIFICIO',
  TRASTERO = 'TRASTERO',
}
