name: daily vercel deployment
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 20 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@master
        with:
          url: https://api.vercel.com/v1/integrations/deploy/QmdQSiWv2hNGAu3pppwBC6UNtMwUSD8hNw8eeMWSHwC5yu/GPVTmxMOQz
