name: daily vercel deployment
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 20 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19.0.1
        with:
          vercel-token: '4nDBl2ZGJhRQwA6aLdRn2r7Y'
          github-comment: false
          vercel-project-id: 'QmdQSiWv2hNGAu3pppwBC6UNtMwUSD8hNw8eeMWSHwC5yu'
          vercel-org-id: 'hnjM1b2rcmt0PrkXfLHwkMVi'
          vercel-args: '--prod'
